### ISSUE TITLE
Mobile responsiveness / Visual UI V.1.1

### ISSUE THREAD

**Issue by temptemp3** [HumbleOSS/humble-interface#1]
Implementation of Design Visual UI V1.1 ([figma](https://www.figma.com/design/WFSJ4rmiDgLx9ocdzZB9w9/Humble-UI-(1.0.0)-AC?node-id=390-14917&node-type=canvas&m=dev)) with focus on mobile responsiveness.

Priorities

- [ ] Layout
- [x] General mobile responsiveness
- [x] Light dark mode
- [ ] Modal
- [ ] Swap
- [ ] Pool
- [ ] Latest modifications
- [ ] Farm (optional, we may take this out and do separately)

Focus

- Improve look and feel and user experience especially for mobile first users
