### ISSUE TITLE
Verified assets

### ISSUE THREAD

**Issue by temptemp3** [HumbleOSS/humble-interface#15]
Add verified assets

Use asset verification status retrieved from api.to show verified logo next to asset as well as display verified assets first in app

- [ ] Add verified assets
- [ ] Document
- [ ] Create repo for github based verification
- [ ] Use assets and verification batches on all page where applicable
- [ ] Add links to asset verification site
